"""Independent scalar reference fixtures for macro VSUB and the VF0 bound failure."""
from pathlib import Path
import struct,json,math
GAME=Path(__file__).resolve().parents[1]
def f(bits):return struct.unpack('<f',struct.pack('<I',bits))[0]
def bits(value):return struct.unpack('<I',struct.pack('<f',value))[0]
def operand(raw):
    exp=raw&0x7f800000
    return f(raw&0x80000000 if exp==0 else ((raw&0x80000000)|0x7f7fffff) if exp==0x7f800000 else raw)
def sub(a,b):
    value=operand(a)-operand(b);sign=0x80000000 if math.copysign(1,value)<0 else 0;flags=2 if sign else 0
    if value==0:return sign,flags|1
    if abs(value)>f(0x7f7fffff):return sign|0x7f7fffff,flags|8
    if abs(value)<f(0x00800000):return sign,flags|5
    return bits(value),flags
fixtures=[([bits(v) for v in (1,-2,3,4)],[bits(v) for v in (1,1,1,4)]),
          ([0x00800001,0x80800001,0x7f7fffff,0xff7fffff],[0x00800000,0x80800000,0xff7fffff,0x7f7fffff]),
          ([0x80000000,1,0x80000001,0x7f800000],[0,0,0,0])]
rows=[]
for left,right in fixtures:
    for op in (0x2c,4,5,6,7,0x24,0x26):
        values=[];flags=[]
        for lane in range(4):
            rhs=right[lane] if op==0x2c else right[op&3] if op<8 else bits(3.0)
            v,flag=sub(left[lane],rhs);values.append(v);flags.append(flag)
        rows.append((op,left,right,values,flags))
assert rows[0][-1]==[1,2,0,1]
assert rows[7][-1]==[5,7,8,10]
# Synthetic mechanism: a discarded VSUB result must not lower the VF0 clamp.
poison=-57556.0
old_bound=int(min(max(poison,poison),32767.0))|1
correct_bound=int(min(max(poison,0.0),32767.0))|1
assert old_bound==-57555 and correct_bound==1
lines=['// Generated by tests/probe-vu-sub.py; scalar expected results, not runtime output.']
for op,left,right,values,flags in rows:
    arr=lambda xs:'{'+','.join(hex(x)+'u' for x in xs)+'}'
    lines.append('{'+','.join((hex(op)+'u',arr(left),arr(right),arr(values),arr(flags)))+'},')
(GAME/'tests/vu-sub-cases.inc').write_text('\n'.join(lines)+'\n')
(GAME/'logs/vu-sub-probe.json').write_text(json.dumps(dict(fixtures=len(rows),native_mask_destination_cases=len(rows)*16*4,
    synthetic_bound_example=dict(old=old_bound,correct=correct_bound,live_causality_verified=False),
    scope='VSUB normal, broadcast, Q and I; immediate macro result/flags; micro pipeline unchanged'),indent=2)+'\n')
print(f'PASS: {len(rows)} scalar fixtures; synthetic VF0 corruption reproduces negative bound {old_bound}')
