"""Check CRI block accounting and retail MPEG private-field instructions.

Ring fixtures model FIFO consumption independently of the C++ loop. They do
not model PS2 IPU bit-level state; the adapter feeds complete blocks to FFmpeg.
"""
import importlib.util
import json
import pathlib
import struct

GAME = pathlib.Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('symbols', GAME/'tests/transfer-prototype-symbols.py')
s = importlib.util.module_from_spec(spec); spec.loader.exec_module(s)
read = s.image(s.ROOT/'MortalKombatShaolinMonks/SLUS_210.87', s.HASHES['retail'])
words = struct.unpack('<18I', read(0x4688b0, 72))
stores = {w & 65535 for w in words if w >> 26 == 43}
assert stores == {0xc4, 0xec, 0xf8, 0xf0, 0xf4}, stores
cases = []
for capacity, start, queued, accepted, partial in ((8,0,5,5,0), (8,6,5,3,17),
        (8,7,1,1,2047), (8,3,0,0,12), (8,2,4,0,9), (8,3,8,8,0)):
    queue = [(start+i) % capacity for i in range(queued)]
    consumed = queue[:accepted]
    remaining = queue[accepted:]
    next_index = remaining[0] if remaining else (start+accepted) % capacity
    cases.append(dict(capacity=capacity, start=start, queued=queued, accepted=accepted,
                      partial=partial, next_index=next_index, remaining=len(remaining), consumed=consumed))
lines = ['// Generated by probe-cri-ring.py; FIFO reference model.']
for c in cases:
    lines.append('{'+','.join(str(c[k]) for k in ('capacity','start','queued','accepted','partial','next_index','remaining'))+'},')
(GAME/'tests/cri_ring_cases.inc').write_text('\n'.join(lines)+'\n')
(GAME/'logs/cri-ring-probe.json').write_text(json.dumps({'passed':True,'elf_sha256':s.HASHES['retail'],
    'picture_field_offsets':sorted(stores),'cases':cases},indent=2)+'\n')
print('PASS: retail MPEG field offsets and 6 FIFO/wrap/backpressure fixtures')
