"""Execute the retail GS display setup with a bounded, fail-closed MIPS probe.

Uses original ELF instructions, independently of the C++ emitter. Covers NTSC
and PAL branches only; no BIOS calibration or unsupported-mode assumptions.
"""
import importlib.util, json, pathlib, struct
GAME = pathlib.Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('symbols', GAME/'tests/transfer-prototype-symbols.py')
s = importlib.util.module_from_spec(spec); spec.loader.exec_module(s)
MASK = (1 << 64) - 1
def signed(x, bits):
    x &= (1 << bits) - 1
    return x - (1 << bits) if x >> (bits - 1) else x

def execute(read, params, args):
    ram = bytearray(0x2000000)
    struct.pack_into('<4H', ram, 0x4edc60, *params)
    r = [0]*32; r[4:10] = [0x90000, *args]; r[29] = 0x1e00000; r[31] = 0x80000
    pc = 0x382f40; pending = None; lo = 0
    for count in range(2000):
        if pc == 0x80000:
            assert r[29] == 0x1e00000
            return list(struct.unpack_from('<5Q', ram, 0x90000))
        w = struct.unpack('<I', read(pc,4))[0]
        op=w>>26; rs=w>>21&31; rt=w>>16&31; rd=w>>11&31; sa=w>>6&31; fn=w&63
        imm=w&65535; si=signed(imm,16); old=pending; pending=None; nxt=pc+4
        if w==0: pass
        elif op==15: r[rt]=signed(imm<<16,32)
        elif op in (9,25): r[rt]=signed(r[rs]+si,32) if op==9 else r[rs]+si
        elif op==11: r[rt]=int(r[rs]<(si&MASK))
        elif op==12: r[rt]=r[rs]&imm
        elif op==13: r[rt]=r[rs]|imm
        elif op in (33,37,35,55):
            size={33:2,37:2,35:4,55:8}[op]; a=(r[rs]+si)&0x1fffffff
            assert a+size<=len(ram)
            r[rt]=int.from_bytes(ram[a:a+size],'little',signed=op in (33,35))
        elif op in (43,63):
            size=4 if op==43 else 8; a=(r[rs]+si)&0x1fffffff
            assert a+size<=len(ram)
            ram[a:a+size]=(r[rt]&((1<<(size*8))-1)).to_bytes(size,'little')
        elif op in (4,5,20,21):
            taken=(r[rs]==r[rt]) == (op in (4,20))
            if taken: pending=pc+4+si*4
            elif op in (20,21): nxt=pc+8
        elif op==3: r[31]=pc+8; pending=((pc+4)&0xf0000000)|((w&0x3ffffff)<<2)
        elif op==0 and fn==8: pending=r[rs]&0xffffffff
        elif op==0 and fn==0: r[rd]=signed(r[rt]<<sa,32)
        elif op==0 and fn==2: r[rd]=signed((r[rt]&0xffffffff)>>sa,32)
        elif op==0 and fn==3: r[rd]=signed(r[rt],32)>>sa
        elif op==0 and fn in (56,60): r[rd]=r[rt]<<(sa+(32 if fn==60 else 0))
        elif op==0 and fn in (33,35): r[rd]=signed(r[rs]+(r[rt] if fn==33 else -r[rt]),32)
        elif op==0 and fn==45: r[rd]=r[rs]+r[rt]
        elif op==0 and fn==37: r[rd]=r[rs]|r[rt]
        elif (op==0 and fn==24) or (op==28 and fn==24):
            product=signed(r[rs],32)*signed(r[rt],32); r[rd]=signed(product,32)
            if op==0: lo=signed(product,32)
        elif op==0 and fn==26:
            a,b=signed(r[rs],32),signed(r[rt],32); assert b!=0
            lo=(abs(a)//abs(b))*(-1 if (a<0)!=(b<0) else 1)
        elif op==0 and fn==18: r[rd]=lo
        else: raise ValueError(f'Unsupported {w:08x} at {pc:x}')
        r=[x&MASK for x in r]; r[0]=0; pc=old if old is not None else nxt
    raise ValueError('Instruction limit exceeded')

def expected(params,args):
    interlace,mode,ff,version=params; psm,width,height,dx,dy=args
    mag=(width+2559)//width
    x=(636 if mode==2 else 656)+dx*mag
    y=(50 if mode==2 else 72) if interlace==1 else (25 if mode==2 else 36)
    lines=height*2 if interlace==1 and ff!=0 else height
    display=((x&4095)|((y+dy)&4095)<<12|(mag-1)<<23|(mag*width-1)<<32|(lines-1)<<44)
    return [0x66, (1 if ff==0 else 3) if interlace else 2,
            (psm&15)<<15|((width+63)//64&63)<<9, display, 0]

def main():
    read=s.image(s.ROOT/'MortalKombatShaolinMonks/SLUS_210.87',s.HASHES['retail'])
    cases=[]
    for mode in (2,3):
        for interlace,ff in ((0,0),(1,0),(1,1)):
            for args in ((0,640,224,0,0),(2,320,240,-4,3)):
                params=(interlace,mode,ff,3); actual=execute(read,params,args)
                assert actual==expected(params,args),(params,args,actual,expected(params,args))
                cases.append({'params':params,'args':args,'registers':actual})
    (GAME/'logs/gs-display-probe.json').write_text(json.dumps({'sha256':s.HASHES['retail'],'passed':True,'cases':cases},indent=2)+'\n')
    lines=['// Generated by probe-gs-display.py from original retail instructions.']
    for case in cases:
        lines.append('{ {'+','.join(map(str,case['params']))+'}, {'+','.join(map(str,case['args']))+'}, {'+','.join(hex(v)+'ull' for v in case['registers'])+'} },')
    (GAME/'tests/gs_display_cases.inc').write_text('\n'.join(lines)+'\n')
    print(f'PASS: {len(cases)} original retail display setups agree with decoded NTSC/PAL fields')
if __name__=='__main__': main()
