"""Generate functional sound lookup tables from formulas; no game files required."""
from pathlib import Path
import math
ROOT=Path(__file__).resolve().parents[1]
# Integer quantization differences established by local compatibility experiments.
pitch=[int(32768*2**(i/1200)) for i in range(1200)]
pitch[853]+=1
pan=[int(100*math.sin(math.radians(i))+.5) for i in range(91)]
for i in (6,13,22,29,33,44,49,61,80,84):pan[i]+=1
lines=['// Generated by tools/generate-audio-tables.py from mathematical formulas.']
for name,values in [('SndfPitchTable',pitch),('SndfPanTable',pan)]:
    lines.append(f'inline constexpr uint16_t {name}[{len(values)}]={{')
    lines.extend(','.join(map(str,values[i:i+20]))+',' for i in range(0,len(values),20))
    lines.append('};')
(ROOT/'ps2xIOP/src/modules/mk_sndf_tables.inc').write_text('\n'.join(lines)+'\n',encoding='utf-8')
